image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build -c Release 'Libota.sln'"
    artifacts:
      paths:
        - Libota.Desktop/bin/Release/net5.0

test:
    stage: test
    script: 
        - "dotnet test ./Tests/UnitTests.csproj"
