using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using CommunityToolkit.Mvvm.Messaging;
using Domain.Users;
using Jamaa.Application.Users.Services;
using Jamaa.Desktop.Security.Events;
using Jamaa.Desktop.Shared;

namespace Jamaa.Desktop.Dashboard;

public partial class DashboardViewModel : ObservableObject, 
    IApplicationModule,
    IRecipient<UserLoggedOut>,
    IRecipient<UserAuthenticated>
{
    private readonly IUserSessionService _userSessionService;
    private readonly IUserRepository _userRepository;

    private static int MaxColumns => 3;
    private static int MaxRows => 2;

    public ObservableCollection<WidgetViewModelBase> ActiveWidgets { get; set; } = [];
    public ObservableCollection<WidgetViewModelBase> AvailableWidgets { get; set; } = [];

    public DashboardViewModel(IUserSessionService userSessionService, IUserRepository userRepository)
    {
        _userSessionService = userSessionService;
        _userRepository = userRepository;
        
        // Register first so we can receive messages
        WeakReferenceMessenger.Default.RegisterAll(this);

        if (_userSessionService.CurrentUserSession is { IsAuthenticated: true })
        {
            _ = LoadLayout(_userSessionService.CurrentUserSession);
        }
        else
        {
            ApplyDefaultGrid();
        }
    }

    public void Receive(UserLoggedOut message)
    {
        _ = SaveLayout();
    }

    public void Receive(UserAuthenticated message)
    {
        _ = LoadLayout(message.Session);
    }

    private bool CanAddWidget(object? parameter)
    {
        if (parameter is object[] values && values.Length == 2 && values[0] is EmptyCellViewModel cell)
        {
            return cell.HasCompatibleWidgets;
        }
        return AvailableWidgets.Any();
    }

    private void UpdateAvailableWidgets()
    {
        var activeTypes = GetActiveWidgetTypes();
        var allPossibleWidgets = CreateAllPossibleWidgets();
        
        AvailableWidgets.Clear();
        PopulateAvailableWidgets(allPossibleWidgets, activeTypes);

        NotifyAllWidgetsOfCompatibility();
        NotifyCommandsCanExecuteChanged();
    }

    private HashSet<Type> GetActiveWidgetTypes() =>
        ActiveWidgets
            .Where(w => w is not EmptyCellViewModel)
            .Select(w => w.GetType())
            .ToHashSet();

    private static List<WidgetViewModelBase> CreateAllPossibleWidgets() =>
    [
        new ReportingAndAnalyticsWidgetViewModel(),
        new BookkeepingWidgetViewModel(),
        new RecentActivityFeedWidgetViewModel(),
        new CalendarScheduleWidgetViewModel(),
        new AlertsAndNotificationsWidgetViewModel(),
        new QuickActionsWidgetViewModel(),
        new MembershipStatsWidgetViewModel()
    ];

    private void PopulateAvailableWidgets(IEnumerable<WidgetViewModelBase> allPossibleWidgets, HashSet<Type> activeTypes)
    {
        foreach (var widget in allPossibleWidgets)
        {
            if (!activeTypes.Contains(widget.GetType()))
            {
                widget.ParentViewModel = this;
                AvailableWidgets.Add(widget);
            }
        }
    }

    private void NotifyAllWidgetsOfCompatibility()
    {
        foreach (var widget in ActiveWidgets)
        {
            widget.NotifyCompatibilityChanged();
        }
    }

    private void NotifyCommandsCanExecuteChanged()
    {
        // Commands are generated by CommunityToolkit.Mvvm from [RelayCommand] attributes
        // and should be accessible by their name + "Command" suffix.
        // If they are not visible in this context, it might be due to a compilation order issue.
    }

    public IEnumerable<WidgetViewModelBase> GetCompatibleWidgets(BoxSize size)
    {
        return AvailableWidgets.Where(w => w.AllowedBoxSize == size);
    }

    [RelayCommand(CanExecute = nameof(CanAddWidget))]
    private void AddWidget(object? parameter)
    {
        if (parameter is not object[] { Length: 2 } values) return;
        if (values[0] is not EmptyCellViewModel cell || values[1] is not WidgetViewModelBase widgetToAdd) return;

        UpdateWidgetPosition(widgetToAdd, cell.Row, cell.Column);
        ActiveWidgets.Remove(cell);
        ActiveWidgets.Add(widgetToAdd);
        
        FinalizeLayoutChange();
    }

    [RelayCommand(CanExecute = nameof(CanReplaceWidget))]
    private void ReplaceWidget(object? parameter)
    {
        if (parameter is not object[] { Length: 2 } values) return;
        if (values[0] is not WidgetViewModelBase oldWidget || values[1] is not WidgetViewModelBase newWidget) return;

        UpdateWidgetPosition(newWidget, oldWidget.Row, oldWidget.Column);
        ActiveWidgets.Remove(oldWidget);
        ActiveWidgets.Add(newWidget);
        
        FinalizeLayoutChange();
    }

    private void RemoveWidget(WidgetViewModelBase? widget)
    {
        if (widget is not { IsRemovable: true }) return;
        
        var emptyCell = CreateEmptyCell(widget.Row, widget.Column);
        ActiveWidgets.Remove(widget);
        ActiveWidgets.Add(emptyCell);
        
        FinalizeLayoutChange();
    }

    private void UpdateWidgetPosition(WidgetViewModelBase widget, int row, int column)
    {
        widget.Row = row;
        widget.Column = column;
        widget.ParentViewModel = this;
        widget.RemoveCommand = new RelayCommand<WidgetViewModelBase>(RemoveWidget);
    }

    private EmptyCellViewModel CreateEmptyCell(int row, int column)
    {
        var boxSize = (column == 1) ? BoxSize.Wide : BoxSize.Small;
        return new EmptyCellViewModel(row, column, boxSize)
        {
            ParentViewModel = this
        };
    }

    private void FinalizeLayoutChange()
    {
        UpdateAvailableWidgets();
        _ = SaveLayout();
    }

    public async Task SaveLayout()
    {
        var userId = _userSessionService.CurrentUserSession?.UserId;
        if (userId == null) return;

        var jsonString = SerializeActiveWidgets();
        await UpdateUserDashboardLayout(userId.Value, jsonString);
    }

    private string SerializeActiveWidgets()
    {
        var options = new JsonSerializerOptions { WriteIndented = true };
        var widgetsToSave = ActiveWidgets.Where(w => w is not EmptyCellViewModel).ToList();
        return JsonSerializer.Serialize(widgetsToSave, options);
    }

    private async Task UpdateUserDashboardLayout(Guid userId, string jsonString)
    {
        var user = await _userRepository.GetById(userId);
        if (user != null)
        {
            user.DashboardLayout = jsonString;
            await _userRepository.Update(user);
        }
    }

    private static bool CanReplaceWidget(object? parameter)
    {
        if (parameter is WidgetViewModelBase widget)
        {
            return widget.HasCompatibleWidgets;
        }

        if (parameter is object[] { Length: 2 } values && values[0] is WidgetViewModelBase oldWidget)
        {
            return oldWidget.HasCompatibleWidgets;
        }

        return false;
    }

    private async Task LoadLayout(Jamaa.Application.Users.UserSession? session = null)
    {
        session ??= _userSessionService.CurrentUserSession;
        if (!IsAuthenticated(session))
        {
            ApplyDefaultGrid();
            return;
        }

        try
        {
            var jsonString = await FetchUserDashboardLayout(session!.UserId!.Value);
            if (jsonString == null)
            {
                ApplyDefaultGrid();
            }
            else
            {
                ApplyLoadedLayout(jsonString);
            }
        }
        catch
        {
            ApplyDefaultGrid();
        }
    }

    private static bool IsAuthenticated(Jamaa.Application.Users.UserSession? session) =>
        session is { IsAuthenticated: true, UserId: not null };

    private async Task<string?> FetchUserDashboardLayout(Guid userId)
    {
        var user = await _userRepository.GetById(userId);
        if (user == null)
        {
            return null;
        }
        return string.IsNullOrWhiteSpace(user.DashboardLayout) ? null : user.DashboardLayout;
    }

    private void ApplyLoadedLayout(string jsonString)
    {
        var loadedWidgets = DeserializeWidgets(jsonString);
        if (loadedWidgets == null || !loadedWidgets.Any())
        {
            ApplyDefaultGrid();
            return;
        }

        LoadDefaultGrid();
        foreach (var widget in loadedWidgets)
        {
            ReconcileWidgetPosition(widget);
        }
        UpdateAvailableWidgets();
    }

    private static ObservableCollection<WidgetViewModelBase>? DeserializeWidgets(string jsonString)
    {
        try
        {
            return JsonSerializer.Deserialize<ObservableCollection<WidgetViewModelBase>>(jsonString);
        }
        catch
        {
            return null;
        }
    }

    private void ReconcileWidgetPosition(WidgetViewModelBase widget)
    {
        UpdateWidgetPosition(widget, widget.Row, widget.Column);

        // Find the corresponding widget to replace
        var existingWidgetAtPosition = ActiveWidgets.FirstOrDefault(w => 
            w.Row == widget.Row && 
            w.Column == widget.Column);

        // Find if this widget type already exists in another position from the default grid
        var existingSameTypeWidget = ActiveWidgets.FirstOrDefault(w => 
            w.GetType() == widget.GetType() && 
            (w.Row != widget.Row || w.Column != widget.Column));

        if (existingSameTypeWidget != null)
        {
            ReplaceWithEmptyCell(existingSameTypeWidget);
        }

        if (existingWidgetAtPosition != null)
        {
            ActiveWidgets.Remove(existingWidgetAtPosition);
        }
        
        ActiveWidgets.Add(widget);
    }

    private void ReplaceWithEmptyCell(WidgetViewModelBase widget)
    {
        var emptyCell = CreateEmptyCell(widget.Row, widget.Column);
        ActiveWidgets.Remove(widget);
        ActiveWidgets.Add(emptyCell);
    }

    private void ApplyDefaultGrid()
    {
        LoadDefaultGrid();
        UpdateAvailableWidgets();
    }

    private void LoadDefaultGrid()
    {
        ActiveWidgets.Clear();
        var defaultWidgets = CreateDefaultWidgets();
        foreach (var widget in defaultWidgets)
        {
            ActiveWidgets.Add(widget);
        }
    }

    private List<WidgetViewModelBase> CreateDefaultWidgets()
    {
        var widgets = new List<WidgetViewModelBase>();
        for (var r = 0; r < MaxRows; r++)
        {
            for (var c = 0; c < MaxColumns; c++)
            {
                var widget = CreateDefaultWidgetAt(r, c);
                widgets.Add(widget);
            }
        }
        return widgets;
    }

    private WidgetViewModelBase CreateDefaultWidgetAt(int r, int c)
    {
        var boxSize = (c == 1) ? BoxSize.Wide : BoxSize.Small;
        WidgetViewModelBase widget = (r, c) switch
        {
            (0, 0) => new MembershipStatsWidgetViewModel(),
            (1, 0) => new RecentActivityFeedWidgetViewModel(),
            (0, 1) => new BookkeepingWidgetViewModel(),
            (1, 1) => new CalendarScheduleWidgetViewModel(),
            (0, 2) => new AlertsAndNotificationsWidgetViewModel(),
            (1, 2) => new QuickActionsWidgetViewModel(),
            _ => new EmptyCellViewModel(r, c, boxSize)
        };

        UpdateWidgetPosition(widget, r, c);
        if (widget is EmptyCellViewModel)
        {
            widget.RemoveCommand = null;
        }
        return widget;
    }

    [RelayCommand]
    private async Task ResetLayout()
    {
        ApplyDefaultGrid();
        await SaveLayout();
    }

    public Guid Id => Guid.Parse("30081491-B585-464D-AED1-BA3782D0E939");
    public string Title => "Dashboard";
    public object? HeaderContent => null;
}