// <auto-generated />
using System;
using Jamaa.Data.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jamaa.Data.Migrations
{
    [DbContext(typeof(JamaaDbContext))]
    partial class JamaaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("OrganisationId", "Code")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountingAvailableCurrencyData", b =>
                {
                    b.Property<string>("OrganisationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrganisationId", "CurrencyCode");

                    b.ToTable("AccountingAvailableCurrencies", (string)null);
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountingPeriodBalanceData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountingPeriodId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ClosingBalance")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalYearId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountingPeriodId");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("OrganisationId", "AccountId", "FiscalYearId", "AccountingPeriodId")
                        .IsUnique();

                    b.ToTable("AccountingPeriodBalances", (string)null);
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountingPeriodData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalYearId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("OrganisationId", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("AccountingPeriods", (string)null);
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountingSettingsData", b =>
                {
                    b.Property<string>("OrganisationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPrecision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThousandSeparator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrganisationId");

                    b.ToTable("AccountingSettings", (string)null);
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.FiscalYearData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FiscalYears", (string)null);
                });

            modelBuilder.Entity("Jamaa.Data.Models.Members.MemberData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PictureData")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Jamaa.Data.Models.Members.RegistrationData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MembershipType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.HasIndex("OrganisationId");

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("Jamaa.Data.Models.Organisation.OrganisationData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Users.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DashboardLayout")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountData", b =>
                {
                    b.HasOne("Jamaa.Data.Models.Finances.AccountData", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountingAvailableCurrencyData", b =>
                {
                    b.HasOne("Jamaa.Data.Models.Finances.AccountingSettingsData", "AccountingSettings")
                        .WithMany("AvailableCurrencies")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountingSettings");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountingPeriodBalanceData", b =>
                {
                    b.HasOne("Jamaa.Data.Models.Finances.AccountData", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jamaa.Data.Models.Finances.AccountingPeriodData", "AccountingPeriod")
                        .WithMany()
                        .HasForeignKey("AccountingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jamaa.Data.Models.Finances.FiscalYearData", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AccountingPeriod");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountingPeriodData", b =>
                {
                    b.HasOne("Jamaa.Data.Models.Finances.FiscalYearData", "FiscalYear")
                        .WithMany("Periods")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Members.MemberData", b =>
                {
                    b.HasOne("Jamaa.Data.Models.Organisation.OrganisationData", "Organisation")
                        .WithMany("Members")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Members.RegistrationData", b =>
                {
                    b.HasOne("Jamaa.Data.Models.Members.MemberData", "Member")
                        .WithOne("Registration")
                        .HasForeignKey("Jamaa.Data.Models.Members.RegistrationData", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jamaa.Data.Models.Organisation.OrganisationData", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.AccountingSettingsData", b =>
                {
                    b.Navigation("AvailableCurrencies");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Finances.FiscalYearData", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("Jamaa.Data.Models.Members.MemberData", b =>
                {
                    b.Navigation("Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("Jamaa.Data.Models.Organisation.OrganisationData", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
