//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamaa.Desktop.Assets.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Jamaa.Desktop.Assets.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string login_error_username {
            get {
                return ResourceManager.GetString("login_error_username", resourceCulture);
            }
        }
        
        internal static string login_error_password {
            get {
                return ResourceManager.GetString("login_error_password", resourceCulture);
            }
        }
        
        internal static string setup_error_username {
            get {
                return ResourceManager.GetString("setup_error_username", resourceCulture);
            }
        }
        
        internal static string setup_error_password {
            get {
                return ResourceManager.GetString("setup_error_password", resourceCulture);
            }
        }
        
        internal static string organisation_name_required {
            get {
                return ResourceManager.GetString("organisation.name.required", resourceCulture);
            }
        }
        
        internal static string organisation_name_length {
            get {
                return ResourceManager.GetString("organisation_name_length", resourceCulture);
            }
        }
        
        internal static string organisation_description_required {
            get {
                return ResourceManager.GetString("organisation_description_required", resourceCulture);
            }
        }
        
        internal static string organisation_description_length {
            get {
                return ResourceManager.GetString("organisation_description_length", resourceCulture);
            }
        }
        
        internal static string setup_error_email {
            get {
                return ResourceManager.GetString("setup_error_email", resourceCulture);
            }
        }
        
        internal static string login_authentication_failed_title {
            get {
                return ResourceManager.GetString("login_authentication_failed_title", resourceCulture);
            }
        }
        
        internal static string login_authentication_failed_message {
            get {
                return ResourceManager.GetString("login_authentication_failed_message", resourceCulture);
            }
        }
        
        internal static string dashboard_available_widgets {
            get {
                return ResourceManager.GetString("dashboard_available_widgets", resourceCulture);
            }
        }
        
        internal static string dashboard_no_widgets_available {
            get {
                return ResourceManager.GetString("dashboard_no_widgets_available", resourceCulture);
            }
        }
    }
}
